config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :spies do
    collection do
      post 'clearance'
    end
  end  

  root "spies#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/spy.rb
class Spy < ApplicationRecord
  after_create_commit { broadcast_append_to('spies', target: 'spies', partial: 'spies/spy_frame', locals: { agent: self }) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable, :lockable, :trackable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :secret_clearance
  before_action :authenticate_user!

  def secret_clearance
    session[:clearance].presence || false
  end
end

app/controllers/spies_controller.rb
class SpiesController < ApplicationController
  before_action :set_spy, only: %i[ show edit update destroy ]

  # GET /spies or /spies.json
  def index
    @spies = Spy.all
  end

  # GET /spies/1 or /spies/1.json
  def show
    if request.headers["turbo-frame"]
      render partial: 'spy', locals: { spy: @spy }
    else
      render 'show'
    end
  end  

  # GET /spies/new
  def new
    @spy = Spy.new
  end

  # GET /spies/1/edit
  def edit
  end

  # POST /spies or /spies.json
  def create
    @spy = Spy.new(spy_params)
  
    respond_to do |format|
      if @spy.save
        format.turbo_stream { render turbo_stream: turbo_stream.replace("new_spy", partial: "spy_link")}
        format.html { redirect_to @spy, notice: "Spy was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @spy.errors, status: :unprocessable_entity }
      end
    end
  end  

  # PATCH/PUT /spies/1 or /spies/1.json
  def update
    respond_to do |format|
      if @spy.update(spy_params)
        format.html { redirect_to @spy, notice: "Spy was successfully updated." }
        format.json { render :show, status: :ok, location: @spy }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @spy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /spies/1 or /spies/1.json
  def destroy
    @spy.destroy
    respond_to do |format|
      format.html { redirect_to spies_url, notice: "Spy was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def clearance
    secret_clearance ? session.delete(:clearance) : session[:clearance] = true
    redirect_to spies_path
  end  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_spy
      @spy = Spy.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def spy_params
      params.require(:spy).permit(:mission).merge(name: current_user.email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/spies_helper.rb
module SpiesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HotwireSpies</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/spies/_form.html.erb
<%= form_with(model: spy) do |form| %>
  <% if spy.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(spy.errors.count, "error") %> prohibited this spy from being saved:</h2>

      <ul>
        <% spy.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :mission %>
    <%= form.text_field :mission %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/spies/_spy.html.erb
<%= turbo_frame_tag spy do %>
  <div>
    <%= spy.name %> | Current mission: <%= current_user.email == spy.name ? spy.mission : "Classified" %>
  </div>
<% end %>

app/views/spies/_spy_frame.html.erb
<%= turbo_frame_tag spy, src: spy_path(spy, frame: true) %>

app/views/spies/_spy_link.html.erb
<%= turbo_frame_tag "new_spy" do %>
  <%= link_to 'New Spy', new_spy_path %>
<% end %>

app/views/spies/edit.html.erb
<h1>Editing Spy</h1>

<%= render 'form', spy: @spy %>

<%= link_to 'Show', @spy %> |
<%= link_to 'Back', spies_path %>

app/views/spies/index.html.erb
Your current clearance is <%= secret_clearance ? "Secret" : "None" %>
<%= link_to "Change clearance", clearance_spies_path, method: :post %>

<h1>Spies</h1>

<%= turbo_stream_from "spies" %>
<div id="spies">
  <% @spies.each do |spy| %>
    <%= render spy, spy: spy %>
  <% end %>
</div>

<br>
<%= render "spy_link" %>

app/views/spies/new.html.erb
<%= turbo_frame_tag "new_spy" do %>
  <%= render 'form', spy: @spy %>
<% end %>

app/views/spies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @spy.name %>
</p>

<p>
  <strong>Mission:</strong>
  <%= @spy.mission %>
</p>

<%= link_to 'Edit', edit_spy_path(@spy) %> |
<%= link_to 'Back', spies_path %>